"""
visible3d - Python script to demonstrate visible facets of convex hulls in the Euclidean n-space.
=================================================================================================
Python script to demonstrate visible facets in Euclidean n-space.

Data is generated by reading a qhull file.  Edit the source to pick a different file.

This program displays no graphics, it just prints the result of the
scipy.spatial ConvexHull routine.

"""
#
# Copyright (C)  Robert T. Short, 2019.
#
# Distributed under the same BSD license as Scipy.
#
import numpy

from scipy.spatial import ConvexHull
from pybob.spatial.qhullfile import readQhullFile

if __name__ == "__main__":

    # Read the qhull file.

    filename = 'qhulldata/spheredata1'

    ndim,points  = readQhullFile(filename)
    npoints = len(points)

    points  = numpy.vstack((points,numpy.zeros(ndim)))

    print(ndim,npoints)
    print(points)

    # Compute the visible and invisible facets.

    qhull_options = "QG-"+str(npoints)
    hull = ConvexHull(points, qhull_options=qhull_options)

    print('Not visible from the origin')
    print(hull.good)
    print(hull.points)
    print(hull.simplices)

    qhull_options = "QG"+str(npoints)
    hull = ConvexHull(points, qhull_options=qhull_options)

    print('Visible from the origin')
    print(hull.good)
    print(hull.points)
    print(hull.simplices)

    print('Visible\n', hull.simplices[hull.good])
    print('Not visible\n', hull.simplices[~hull.good])

